import { CognitiveCore } from '@novus/cognitive-core';
import { LearningEngine } from '@novus/learning-engine';
import { DEFAULT_LOCALE, distance, localizeTerm, simulationCs, uid, type Agent, type AgentAction, type AIMode, type Decision, type EventCategory, type Memory, type MindDecisionContext, type Position, type SimulationState, type TileType } from '@novus/shared';
import { generateWorld, seededRandom } from '@novus/world-generator';

const NAMES=['Nara','Tovan','Seli','Orin','Mira','Eron','Lea','Aron','Lena','Iven','Roa','Kael','Veya','Daro','Uma','Pavel','Ilya','Sen','Tali','Bren','Alma','Ciro','Nemi','Osa','Yara'];
const CHARACTERS=simulationCs.characters;
const CLOTH=simulationCs.clothing;
const SKIN=['#6f4938','#946348','#b47b55','#c79067','#dda878','#8a5940'];const HAIR=['#211b18','#4a3021','#6c4a30','#b28757','#d4c4a2'];
const WALKABLE=new Set<TileType>(['grass','dirt','fertile','sand','shallow_water']);
const usageTotals=()=>({requestCount:0,successCount:0,failureCount:0,fallbackCount:0,staleCount:0,totalLatencyMs:0,inputTokens:0,outputTokens:0});
const researchCounters=()=>({reflections:0,beliefChanges:0,questionsCreated:0,questionsRevisited:0,intentionsCompleted:0,intentionsAbandoned:0,contradictions:0,knowledgeTransfers:0});
const mindState=()=>({intentionSinceTick:0,lastRelevantMemoryIds:[],identityDevelopments:[],recentFailures:[],recentSuccesses:[],visitedRegions:[]});

export function tileAt(state:SimulationState,x:number,y:number){return state.tiles[y*state.width+x]}
export function isWalkable(state:SimulationState,x:number,y:number){if(x<0||y<0||x>=state.width||y>=state.height)return false;const tile=tileAt(state,x,y);return !!tile&&WALKABLE.has(tile.type)&&!state.structures.some(s=>s.progress>=1&&s.x===x&&s.y===y&&s.primitives.includes('WOOD_WALL'))&&!state.objects.some(o=>o.blocks&&o.x===x&&o.y===y)}

export function findPath(state:SimulationState,start:Position,goal:Position,maxNodes=3500):Position[]{
  goal={x:Math.max(0,Math.min(state.width-1,Math.round(goal.x))),y:Math.max(0,Math.min(state.height-1,Math.round(goal.y)))};
  if(!isWalkable(state,goal.x,goal.y)){for(let r=1;r<8;r++){let found:Position|undefined;for(let dy=-r;dy<=r&&!found;dy++)for(let dx=-r;dx<=r;dx++)if(isWalkable(state,goal.x+dx,goal.y+dy)){found={x:goal.x+dx,y:goal.y+dy};break}if(found){goal=found;break}}}
  const key=(p:Position)=>`${p.x},${p.y}`, h=(p:Position)=>Math.abs(p.x-goal.x)+Math.abs(p.y-goal.y);const open=[{...start,g:0,f:h(start)}];const came=new Map<string,Position>();const costs=new Map([[key(start),0]]);let visited=0;
  while(open.length&&visited++<maxNodes){open.sort((a,b)=>a.f-b.f);const current=open.shift()!;if(current.x===goal.x&&current.y===goal.y){const path:Position[]=[];let cur:Position=current;while(key(cur)!==key(start)){path.unshift({x:cur.x,y:cur.y});cur=came.get(key(cur))!}return path}
    for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const next={x:current.x+dx,y:current.y+dy};if(!isWalkable(state,next.x,next.y))continue;const terrain=tileAt(state,next.x,next.y).type;const g=current.g+(terrain==='shallow_water'?3:1);if(g<(costs.get(key(next))??Infinity)){costs.set(key(next),g);came.set(key(next),current);open.push({...next,g,f:g+h(next)})}}
  }return [];
}

export class ActionValidator {
  validate(state:SimulationState,agent:Agent,action:AgentAction){const allowed=['WAIT','MOVE','SPEAK','INSPECT','PICK_UP','DROP','GATHER','PLACE','BUILD','USE','CRAFT_EXPERIMENT','GIVE','TAKE','WRITE','READ'];if(!allowed.includes(action.type))return {valid:false,reason:simulationCs.unknownAction};if(action.target&&(action.target.x<0||action.target.y<0||action.target.x>=state.width||action.target.y>=state.height))return {valid:false,reason:simulationCs.outsideWorld};if(action.description&&action.description.length>500)return {valid:false,reason:simulationCs.descriptionTooLong};return {valid:true,reason:''}}
}

function createAgent(index:number,state:SimulationState,random:()=>number):Agent{
  let x=45+Math.floor(random()*16),y=42+Math.floor(random()*18);while(!isWalkable(state,x,y)){x=35+Math.floor(random()*30);y=35+Math.floor(random()*30)}const name=NAMES[index];
  return {id:`agent_${index+1}`,name,age:19+Math.floor(random()*29),appearance:{skin:SKIN[Math.floor(random()*SKIN.length)],hair:HAIR[Math.floor(random()*HAIR.length)],clothing:CLOTH[Math.floor(random()*CLOTH.length)],accessory:random()<.25?'tkaná šňůrka':'žádný',body:['slight','average','broad'][Math.floor(random()*3)] as any},character:CHARACTERS[index%CHARACTERS.length],biography:simulationCs.biography(name),x,y,activity:simulationCs.initialActivity,intention:simulationCs.initialIntention,thoughtSummary:simulationCs.initialThought,sensations:[simulationCs.rested,simulationCs.comfortableTemperature],health:1,hunger:.18+random()*.12,thirst:.18+random()*.12,fatigue:.08+random()*.12,temperature:.5,inventory:[],memories:[],beliefs:[],skills:[],motivations:[{id:`mot_${index}`,text:simulationCs.initialMotivations[index%2],strength:.55+random()*.25,source:'initial disposition',createdTick:0}],questions:[simulationCs.initialQuestions[index%3]],knownPeople:[],conversations:[],history:[{id:`history_start_${index}`,day:1,tick:0,text:simulationCs.firstAwareness,category:'Other'}],reflections:[],actionHistory:[],recentObservations:['Krajina obsahuje vodu, vegetaci, kámen a další neznámé lidi.'],namedConcepts:[],path:[],action:undefined,actionStartedTick:0,lastDecisionTick:-index*5,lastReflectionTick:0,aiStatus:'idle',mind:mindState()};
}

export function createWorld(seed=78142,population=10):SimulationState{
  const generated=generateWorld(seed,100,100);const state:SimulationState={id:'novus_primary',name:simulationCs.worldName,locale:DEFAULT_LOCALE,seed,width:100,height:100,tiles:generated.tiles,objects:generated.objects,structures:[],agents:[],events:[],concepts:[],experiments:[],researchMarkers:[],experiences:[],tick:0,year:1,day:1,hour:6,speed:1,paused:false,weather:'clear',weatherUntil:160,status:'running',ai:{mode:'MOCK',provider:'deterministic-cognitive-core',model:'deterministic-cognitive-core',endpoint:'',thinkingMode:'auto',configured:true,pending:0,lastRequestLatencyMs:0,totals:usageTotals(),byAgent:{},research:researchCounters()},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const random=seededRandom(seed+99);for(let i=0;i<Math.max(1,Math.min(25,population));i++)state.agents.push(createAgent(i,state,random));addEvent(state,'Other',simulationCs.firstWorldEvent,state.agents.map(a=>a.id),true);return state;
}

export function addEvent(state:SimulationState,category:EventCategory,text:string,agentIds:string[]=[],important=false){const event={id:uid('event',state.tick),tick:state.tick,day:state.day,hour:state.hour,category,text,agentIds,important};state.events.push(event);if(state.events.length>700)state.events.shift();return event}
function addMemory(state:SimulationState,agent:Agent,text:string,type:Memory['type']='working',importance=.4,participants:string[]=[]){const m:Memory={id:uid('memory',state.tick),tick:state.tick,day:state.day,type,text,importance,participants,location:{x:agent.x,y:agent.y},tags:text.toLowerCase().match(/[a-z]{4,}/g)?.slice(0,5)||[]};agent.memories.push(m);if(agent.memories.length>260)agent.memories.splice(0,agent.memories.length-260);return m}
function history(state:SimulationState,agent:Agent,text:string,category:EventCategory){if(agent.history.some(h=>h.text===text&&state.tick-h.tick<40))return;agent.history.push({id:uid('history',state.tick),day:state.day,tick:state.tick,text,category})}
function marker(state:SimulationState,label:string,description:string){if(state.researchMarkers.some(m=>m.label===label))return;state.researchMarkers.push({id:uid('marker',state.tick),tick:state.tick,day:state.day,label,description});addEvent(state,'Discovery',`Výzkumný milník: ${label} — ${description}`,[],true)}

function updateBody(agent:Agent,state:SimulationState){agent.hunger=Math.min(1,agent.hunger+.0008);agent.thirst=Math.min(1,agent.thirst+(state.weather==='rain'?.00045:.0009));agent.fatigue=Math.min(1,Math.max(0,agent.fatigue+(agent.activity.includes('Odpoč')||agent.activity.includes('Rest')?-.006:.00065)));const s:string[]=[];if(agent.hunger>.76)s.push(simulationCs.sensations.hungry);else if(agent.hunger>.48)s.push(simulationCs.sensations.mildHunger);if(agent.thirst>.7)s.push(simulationCs.sensations.thirsty);else if(agent.thirst>.46)s.push(simulationCs.sensations.dryMouth);if(agent.fatigue>.75)s.push(simulationCs.sensations.exhausted);else if(agent.fatigue>.48)s.push(simulationCs.sensations.tired);if(state.weather==='rain')s.push(simulationCs.sensations.rain);else if(state.hour<6||state.hour>20)s.push(simulationCs.sensations.coolNight);else s.push(simulationCs.sensations.comfortable);agent.sensations=s.length?s:[simulationCs.rested,simulationCs.sensations.physicallyComfortable]}

function socialMemory(agent:Agent,other:Agent,text:string,state:SimulationState){let kp=agent.knownPeople.find(p=>p.agentId===other.id);if(!kp){kp={agentId:other.id,name:other.name,impressions:[simulationCs.unfamiliar],rememberedInteractions:[]};agent.knownPeople.push(kp)}kp.rememberedInteractions.push(text);if(kp.rememberedInteractions.length>12)kp.rememberedInteractions.shift();if(kp.rememberedInteractions.length>2&&!kp.impressions.includes(simulationCs.familiar))kp.impressions.push(simulationCs.familiar);if(/dobrovolně dal/i.test(text)&&!kp.impressions.includes('nápomocný'))kp.impressions.push('nápomocný');if(kp.rememberedInteractions.length>6&&!kp.impressions.includes('důvěryhodný na základě zkušenosti'))kp.impressions.push('důvěryhodný na základě zkušenosti');addMemory(state,agent,text,'social',.58,[other.id])}

export class Simulation {
  state:SimulationState; cognitive=new CognitiveCore(); learning=new LearningEngine(); validator=new ActionValidator(); private random:()=>number;
  constructor(state?:SimulationState,seed=78142,population=10,mode:AIMode='MOCK'){this.state=state||createWorld(seed,population);this.state.locale||=DEFAULT_LOCALE;this.state.ai||={mode,provider:mode==='MOCK'?'deterministic-cognitive-core':'unconfigured',model:mode==='MOCK'?'deterministic-cognitive-core':'',endpoint:'',thinkingMode:'auto',configured:mode==='MOCK',pending:0,lastRequestLatencyMs:0,totals:usageTotals(),byAgent:{},research:researchCounters()};this.state.ai.mode=mode;this.state.ai.model||=this.state.ai.provider;this.state.ai.endpoint||='';this.state.ai.thinkingMode||='auto';this.state.ai.lastRequestLatencyMs||=0;this.state.ai.pending=0;this.state.ai.totals={...usageTotals(),...this.state.ai.totals};this.state.ai.research={...researchCounters(),...this.state.ai.research};for(const agent of this.state.agents){agent.mind||=mindState();agent.mind.lastRelevantMemoryIds||=[];agent.mind.identityDevelopments||=[];agent.mind.recentFailures||=[];agent.mind.recentSuccesses||=[];agent.mind.visitedRegions||=[];agent.mind.pendingRequestId=undefined;agent.aiStatus='idle';if(agent.memories.length>260)agent.memories=agent.memories.slice(-260);if(agent.questions.length>24)agent.questions=agent.questions.slice(0,24);const distinctMotivations=new Map<string,(typeof agent.motivations)[number]>();for(const motivation of agent.motivations)distinctMotivations.set(`${motivation.source}:${motivation.text}`,motivation);agent.motivations=[...distinctMotivations.values()].slice(-12)}this.random=seededRandom(this.state.seed+this.state.tick*17+41)}
  setAIMode(mode:AIMode,provider=mode==='MOCK'?'deterministic-cognitive-core':'unconfigured',configured=mode==='MOCK',details:Partial<Pick<SimulationState['ai'],'model'|'endpoint'|'thinkingMode'>>={}){this.state.ai.mode=mode;this.state.ai.provider=provider;this.state.ai.model=details.model||provider;this.state.ai.endpoint=details.endpoint||'';this.state.ai.thinkingMode=details.thinkingMode||'auto';this.state.ai.configured=configured;this.state.ai.pending=0;for(const agent of this.state.agents){agent.mind.pendingRequestId=undefined;agent.aiStatus='idle'}return this.state.ai}
  settings(patch:Partial<Pick<SimulationState,'paused'|'speed'>>){if(typeof patch.paused==='boolean'){this.state.paused=patch.paused;this.state.status=patch.paused?'paused':'running'}if([1,2,5,10].includes(patch.speed as number))this.state.speed=patch.speed!;return this.state}
  tick(){if(this.state.paused)return this.state;this.state.tick++;this.state.day=Math.floor(this.state.tick/240)+1;this.state.year=Math.floor((this.state.day-1)/365)+1;this.state.hour=(this.state.tick%240)/10;this.state.updatedAt=new Date().toISOString();
    if(this.state.tick>=this.state.weatherUntil){const roll=this.random();this.state.weather=roll<.23?'rain':roll<.51?'cloudy':'clear';this.state.weatherUntil=this.state.tick+100+Math.floor(this.random()*220);addEvent(this.state,'Other',simulationCs.weatherShift(localizeTerm(this.state.weather)))}
    for(const agent of this.state.agents){updateBody(agent,this.state);this.continueAction(agent);const region=`${Math.floor(agent.x/10)},${Math.floor(agent.y/10)}`;if(!agent.mind.visitedRegions.includes(region))agent.mind.visitedRegions.push(region);if(this.decisionDue(agent)&&this.state.ai.mode==='MOCK')this.decide(agent);if(this.state.tick-agent.lastReflectionTick>360&&this.state.tick%37===Number(agent.id.split('_')[1]))this.consolidate(agent)}return this.state;
  }
  decisionDue(agent:Agent){return this.state.tick-agent.lastDecisionTick>=18+Number(agent.id.split('_')[1])%9&&!agent.path.length&&!agent.mind.pendingRequestId}
  prepareLivingMindRequest(agentId:string,requestId:string):MindDecisionContext|null{const agent=this.state.agents.find(item=>item.id===agentId);if(!agent||this.state.ai.mode!=='LIVING_MIND'||!this.decisionDue(agent))return null;const repetitive=this.learning.pattern.detect(agent).repetitive;const context=this.cognitive.buildMindContext(this.state,agent,repetitive);agent.lastDecisionTick=this.state.tick;agent.mind.pendingRequestId=requestId;agent.mind.pendingSinceTick=this.state.tick;agent.aiStatus='queued';this.state.ai.pending++;return context}
  fallbackDecision(agentId:string):Decision{const agent=this.state.agents.find(item=>item.id===agentId);if(!agent)return {thought_summary:simulationCs.ai.fallbackThought,current_intention:simulationCs.ai.fallbackIntention,action:{type:'WAIT'},speech:null};return this.cognitive.decide(this.state,agent,this.random,this.learning.pattern.detect(agent).repetitive).decision}
  applyLivingMindDecision(result:{agentId:string;requestId:string;requestedTick:number;decision:Decision;provider:string;model:string;latencyMs:number;fallback:boolean;error?:string;usage?:{inputTokens:number;outputTokens:number}}){const agent=this.state.agents.find(item=>item.id===result.agentId);const totals=this.state.ai.totals;this.state.ai.lastRequestLatencyMs=result.latencyMs;totals.requestCount++;totals.totalLatencyMs+=result.latencyMs;totals.inputTokens+=result.usage?.inputTokens||0;totals.outputTokens+=result.usage?.outputTokens||0;const perAgent=this.state.ai.byAgent[result.agentId]||=( {agentId:result.agentId,...usageTotals()} );perAgent.requestCount++;perAgent.totalLatencyMs+=result.latencyMs;perAgent.inputTokens+=result.usage?.inputTokens||0;perAgent.outputTokens+=result.usage?.outputTokens||0;if(result.fallback){totals.fallbackCount++;perAgent.fallbackCount++;totals.failureCount++;perAgent.failureCount++;this.state.ai.lastError=result.error}else{totals.successCount++;perAgent.successCount++}this.state.ai.pending=Math.max(0,this.state.ai.pending-1);const matches=agent?.mind.pendingRequestId===result.requestId;if(!agent||!matches||this.state.tick-result.requestedTick>180){if(matches){agent.mind.pendingRequestId=undefined;agent.mind.pendingSinceTick=undefined;agent.aiStatus='idle'}totals.staleCount++;perAgent.staleCount++;return false}agent.mind.pendingRequestId=undefined;agent.mind.pendingSinceTick=undefined;agent.aiStatus=result.fallback?'backoff':'idle';this.applyDecision(agent,result.decision,result.requestId);return true}
  failLivingMindRequest(agentId:string,requestId:string,error:string){const agent=this.state.agents.find(item=>item.id===agentId);this.state.ai.pending=Math.max(0,this.state.ai.pending-1);this.state.ai.totals.failureCount++;this.state.ai.lastError=error;if(agent?.mind.pendingRequestId===requestId){agent.mind.pendingRequestId=undefined;agent.aiStatus='backoff'} }
  private continueAction(agent:Agent){if(agent.path.length){const next=agent.path.shift()!;agent.x=next.x;agent.y=next.y;agent.activity=agent.action?.type==='MOVE'?simulationCs.walking:simulationCs.approaching(agent.action?.type.toLowerCase().replace('_',' ')||'');if(this.state.tick%5===0)addEvent(this.state,'Movement',simulationCs.movement(agent.name,localizeTerm(tileAt(this.state,agent.x,agent.y).type.replace('_',' '))),[agent.id]);if(!agent.path.length&&agent.action&&agent.action.type!=='MOVE')this.resolve(agent,agent.action);else if(!agent.path.length){agent.activity=simulationCs.lookingAfterWalk;addMemory(this.state,agent,simulationCs.arrived(localizeTerm(tileAt(this.state,agent.x,agent.y).type.replace('_',' '))),'episodic',.35);}}else if(agent.action?.type==='WAIT'&&this.state.tick-agent.actionStartedTick>8){agent.action=undefined;agent.activity=simulationCs.resting;agent.fatigue=Math.max(0,agent.fatigue-.08)}}
  private decide(agent:Agent){agent.lastDecisionTick=this.state.tick;const repetitive=this.learning.pattern.detect(agent).repetitive;const {decision}=this.cognitive.decide(this.state,agent,this.random,repetitive);if(repetitive){addEvent(this.state,'Discovery',simulationCs.repetition(agent.name),[agent.id]);const text=agent.questions[0]||simulationCs.noveltyMotivation;if(!agent.motivations.some(motivation=>motivation.source==='repetition detected'&&motivation.text===text))agent.motivations.push({id:uid('novelty',this.state.tick),text,strength:.82,source:'repetition detected',createdTick:this.state.tick});if(agent.motivations.length>12)agent.motivations=agent.motivations.slice(-12);this.state.ai.research.questionsRevisited++}this.applyDecision(agent,decision)}
  private applyDecision(agent:Agent,decision:Decision,requestId?:string){const previous=agent.intention;const age=this.state.tick-agent.mind.intentionSinceTick;const canChange=previous===decision.current_intention||age>=90||Boolean(decision.reason_for_change);if(canChange&&previous!==decision.current_intention){if(decision.reason_for_change){agent.mind.intentionReason=decision.reason_for_change;this.state.ai.research.intentionsAbandoned++}agent.intention=decision.current_intention;agent.mind.intentionSinceTick=this.state.tick}else if(!canChange){decision.current_intention=previous}agent.thoughtSummary=decision.thought_summary;agent.mind.expectedOutcome=decision.expected_outcome;if(decision.question&&!agent.questions.includes(decision.question)){agent.questions.unshift(decision.question);if(agent.questions.length>24)agent.questions.length=24;this.state.ai.research.questionsCreated++}agent.action=decision.action;agent.actionStartedTick=this.state.tick;agent.actionHistory.push(decision.action);if(agent.actionHistory.length>80)agent.actionHistory.shift();this.resolve(agent,decision.action);const experience=this.state.experiences.at(-1);if(experience&&experience.agentId===agent.id&&requestId)experience.requestId=requestId}
  private resolve(agent:Agent,action:AgentAction){const checked=this.validator.validate(this.state,agent,action);if(!checked.valid){this.finish(agent,action,simulationCs.invalidAction(checked.reason));return}if(action.target&&distance(agent,action.target)>2&&action.type!=='MOVE'){agent.path=findPath(this.state,agent,action.target);if(agent.path.length){agent.activity=simulationCs.approaching(action.type.toLowerCase().replace('_',' '));return}}
    switch(action.type){case 'MOVE':{const target=action.target||{x:agent.x,y:agent.y};agent.path=findPath(this.state,{x:agent.x,y:agent.y},target);agent.activity=agent.path.length?'Putuje k neznámému místu':'Po neúspěšném hledání cesty se zastavil';if(!agent.path.length)this.finish(agent,action,simulationCs.noRoute);break}
      case 'WAIT':agent.activity='Odpočívá a pozoruje okolí';break;
      case 'INSPECT':{const object=this.state.objects.find(o=>o.id===action.objectId);const text=object?simulationCs.inspectObject(object.description,localizeTerm(tileAt(this.state,object.x,object.y).type.replace('_',' '))):simulationCs.inspectGround(localizeTerm(tileAt(this.state,agent.x,agent.y).type.replace('_',' ')));agent.recentObservations.push(text);const question=object?simulationCs.objectQuestion(localizeTerm(object.kind)):simulationCs.groundQuestion;if(!agent.questions.includes(question)){agent.questions.unshift(question);this.state.ai.research.questionsCreated++;if(agent.questions.length>24)agent.questions.length=24}this.finish(agent,action,text,'Discovery');break}
      case 'GATHER':{const object=this.state.objects.find(o=>o.id===action.objectId);if(!object){this.finish(agent,action,simulationCs.gone);break}const existing=agent.inventory.find(i=>i.kind===object.kind);if(existing)existing.amount++;else agent.inventory.push({kind:object.kind,amount:1,description:object.description});object.amount--;if(object.amount<=0)this.state.objects=this.state.objects.filter(o=>o.id!==object.id);if(object.kind==='berries'){agent.hunger=Math.max(0,agent.hunger-.18);agent.thirst=Math.max(0,agent.thirst-.06)}this.finish(agent,action,simulationCs.gathered(object.description,localizeTerm(tileAt(this.state,agent.x,agent.y).type.replace('_',' '))),'Other');break}
      case 'SPEAK':{const other=this.state.agents.find(a=>a.id===action.targetAgentId);if(!other||distance(agent,other)>12){this.finish(agent,action,simulationCs.unheard);break}const text=action.speech||simulationCs.genericSpeech;const c={id:uid('conversation',this.state.tick),tick:this.state.tick,withAgentId:other.id,speaker:agent.name,text};agent.conversations.push(c);other.conversations.push({...c,withAgentId:agent.id});socialMemory(agent,other,simulationCs.spokeMemory(other.name,text),this.state);socialMemory(other,agent,simulationCs.heardMemory(agent.name,text),this.state);if(agent.beliefs.length&&this.random()<.5){const b=agent.beliefs[Math.floor(this.random()*agent.beliefs.length)];other.beliefs.push({...b,id:uid('heard_belief',this.state.tick),status:'UNCERTAIN',confidence:Math.min(.42,b.confidence),evidence:[simulationCs.heardBelief(agent.name,b.statement)],updatedTick:this.state.tick});this.state.ai.research.knowledgeTransfers++}addEvent(this.state,'Communication',simulationCs.spokeEvent(agent.name,other.name,text),[agent.id,other.id]);history(this.state,agent,simulationCs.spokeHistory(other.name),'Communication');this.finish(agent,action,simulationCs.spokeResult(other.name));break}
      case 'CRAFT_EXPERIMENT':{const materials=agent.inventory.slice(0,2).map(i=>i.kind);if(materials.length<2){this.finish(agent,action,simulationCs.experimentNeedsMaterials,'Experimentation');break}const score=(materials.includes('branch')?.32:0)+(materials.includes('stone')?.28:0)+(materials.includes('bush')?.18:0)+this.random()*.45;const outcome=score>.72?'success':score>.48?'partial':score<.15?'unexpected':'failure';const [a,b]=materials.map(localizeTerm);const observation=outcome==='success'?simulationCs.experimentHeld(a,b):outcome==='partial'?simulationCs.experimentPartial(a,b):outcome==='unexpected'?simulationCs.experimentUnexpected(a,b):simulationCs.experimentFailed(a,b);this.state.experiments.push({id:uid('experiment',this.state.tick),agentId:agent.id,tick:this.state.tick,description:action.description||simulationCs.experimentDescription,materials,outcome,observation});if(outcome==='success'){marker(this.state,simulationCs.firstExperiment,simulationCs.firstExperimentDescription(agent.name));if(!this.state.concepts.length){const name=simulationCs.bindingName(agent.name);this.state.concepts.push({id:uid('concept',this.state.tick),name,creatorId:agent.id,description:simulationCs.bindingDescription(materials.map(localizeTerm).join(' a ')),firstUsage:this.state.tick,knownBy:[agent.id]});agent.namedConcepts.push(name);marker(this.state,simulationCs.firstName,simulationCs.firstNameDescription(agent.name,name))}}this.finish(agent,action,observation,'Experimentation');break}
      case 'BUILD':{const branches=agent.inventory.find(i=>i.kind==='branch');if(!branches?.amount){this.finish(agent,action,simulationCs.buildNeedsMaterial,'Construction');break}branches.amount--;if(branches.amount<=0)agent.inventory=agent.inventory.filter(i=>i!==branches);const target=action.target||{x:agent.x+1,y:agent.y};const wet=tileAt(this.state,Math.max(0,Math.min(99,target.x)),Math.max(0,Math.min(99,target.y))).moisture;const success=this.random()>wet*.45;const structure={id:uid('structure',this.state.tick),creatorId:agent.id,x:target.x,y:target.y,primitives:['WOOD_WALL','ROOF'],description:action.description||simulationCs.unnamedCover,progress:success?1:.45,createdTick:this.state.tick};this.state.structures.push(structure);const result=success?simulationCs.buildHeld:simulationCs.buildSagged;if(success)marker(this.state,simulationCs.firstConstruction,simulationCs.firstConstructionDescription(agent.name));this.finish(agent,action,result,'Construction');break}
      case 'GIVE':{const other=this.state.agents.find(a=>a.id===action.targetAgentId),item=agent.inventory[0];if(!other||!item||distance(agent,other)>2){this.finish(agent,action,simulationCs.exchangeFailed);break}item.amount--;if(item.amount<=0)agent.inventory.shift();const theirs=other.inventory.find(i=>i.kind===item.kind);if(theirs)theirs.amount++;else other.inventory.push({...item,amount:1});socialMemory(other,agent,simulationCs.giftMemory(agent.name,item.description),this.state);marker(this.state,simulationCs.firstGift,simulationCs.firstGiftDescription(agent.name,other.name,localizeTerm(item.kind)));this.finish(agent,action,simulationCs.gave(other.name,item.description),'Social');break}
      case 'WRITE':{const note={id:uid('note',this.state.tick),x:agent.x,y:agent.y,kind:'note' as const,amount:1,description:action.description||simulationCs.object.note(agent.name)};this.state.objects.push(note);marker(this.state,simulationCs.firstNote,simulationCs.firstNoteDescription(agent.name));this.finish(agent,action,simulationCs.notePlaced,'Discovery');break}
      default:this.finish(agent,action,simulationCs.genericCompletion(action.type));}
  }
  private finish(agent:Agent,action:AgentAction,result:string,category:EventCategory='Other'){const concise=result.replace(/^(I |Já )/,'');agent.activity=concise.slice(0,90);agent.recentObservations.push(result);if(agent.recentObservations.length>12)agent.recentObservations.shift();const importance=this.learning.evaluator.importance(result);addMemory(this.state,agent,result,importance>.7?'episodic':'working',importance);const failed=/(selhal|nepodař|nenašel|nebyl|nemohl|rozpadl)/i.test(result);const succeeded=/(vydrž|vytvoř|sebral|dorazil|mluvil)/i.test(result);if(failed){agent.mind.recentFailures.push(result);if(agent.mind.recentFailures.length>8)agent.mind.recentFailures.shift();if(agent.mind.recentFailures.length>=3&&!agent.motivations.some(m=>m.source==='repeated failure'))agent.motivations.push({id:uid('failure_motivation',this.state.tick),text:simulationCs.cognition.failureConcern,strength:.68,source:'repeated failure',createdTick:this.state.tick})}if(succeeded){agent.mind.recentSuccesses.push(result);if(agent.mind.recentSuccesses.length>8)agent.mind.recentSuccesses.shift();if(agent.mind.recentSuccesses.length>=3&&!agent.motivations.some(m=>m.source==='repeated success'))agent.motivations.push({id:uid('success_motivation',this.state.tick),text:simulationCs.cognition.repeatedSuccessInterest,strength:.56,source:'repeated success',createdTick:this.state.tick})}this.learning.process(this.state,agent,action,result);addEvent(this.state,category,`${agent.name}: ${concise}`,[agent.id],importance>.7);if(importance>.7)history(this.state,agent,concise,category);if(agent.mind.expectedOutcome&&succeeded){this.state.ai.research.intentionsCompleted++;agent.mind.expectedOutcome=undefined}if(this.cognitive.reflection.shouldReflect(agent,result,this.state.tick)){const reflection=this.cognitive.reflection.summarize(agent,result);agent.reflections.push({id:uid('reflection',this.state.tick),tick:this.state.tick,summary:reflection,trigger:result});agent.lastReflectionTick=this.state.tick;this.state.ai.research.reflections++;this.cognitive.identity.evolve(agent,reflection);if(agent.character.includes('opatr')&&!agent.mind.identityDevelopments.includes(simulationCs.cognition.identityCaution.trim()))agent.mind.identityDevelopments.push(simulationCs.cognition.identityCaution.trim());const exp=this.state.experiences.at(-1);if(exp)exp.reflection=reflection}if(action.type!=='WAIT'&&action.type!=='MOVE')agent.action=undefined}
  private consolidate(agent:Agent){const memory=this.learning.memory.consolidate(agent,this.state.tick);if(memory){if(agent.memories.length>260)agent.memories.splice(0,agent.memories.length-260);agent.lastReflectionTick=this.state.tick;agent.reflections.push({id:uid('reflection',this.state.tick),tick:this.state.tick,summary:simulationCs.consolidationReflection(memory.text.slice(0,180)),trigger:'memory consolidation'});this.state.ai.research.reflections++;addEvent(this.state,'Discovery',simulationCs.consolidationEvent(agent.name),[agent.id])}}
}

export const serializeState=(state:SimulationState)=>JSON.stringify(state);
export const deserializeState=(value:string)=>JSON.parse(value) as SimulationState;
