import { describe, expect, it } from 'vitest';
import { AIRequestScheduler, type AIProvider, type AIProviderResult } from '@novus/ai';
import { CognitiveCore, ReflectionEngine } from '@novus/cognitive-core';
import { LearningEngine } from '@novus/learning-engine';
import type { Decision, Memory, MindDecisionContext } from '@novus/shared';
import { createWorld, Simulation } from './index';

const waitDecision:Decision={thought_summary:'Po předchozí zkušenosti chce chvíli pozorovat.',current_intention:'Pozorovat okolí.',action:{type:'WAIT'},speech:null};

describe('Phase 2 Living Mind continuity',()=>{
  it('keeps MOCK deterministic and switches modes explicitly',()=>{const simulation=new Simulation(createWorld(12,2));expect(simulation.state.ai.mode).toBe('MOCK');simulation.setAIMode('LIVING_MIND','test-provider',true);expect(simulation.state.ai).toMatchObject({mode:'LIVING_MIND',provider:'test-provider',configured:true});simulation.setAIMode('MOCK');expect(simulation.state.ai.mode).toBe('MOCK')});
  it('persists a recent intention when no reason for change is supplied',()=>{const simulation=new Simulation(createWorld(2,1),2,1,'LIVING_MIND');const agent=simulation.state.agents[0];agent.lastDecisionTick=-100;const original=agent.intention;const context=simulation.prepareLivingMindRequest(agent.id,'request_1');expect(context).not.toBeNull();simulation.applyLivingMindDecision({agentId:agent.id,requestId:'request_1',requestedTick:0,decision:{...waitDecision,current_intention:'Úplně jiný záměr.'},provider:'test',model:'test',latencyMs:5,fallback:false});expect(agent.intention).toBe(original)});
  it('accepts a justified intention change',()=>{const simulation=new Simulation(createWorld(2,1),2,1,'LIVING_MIND');const agent=simulation.state.agents[0];agent.lastDecisionTick=-100;simulation.prepareLivingMindRequest(agent.id,'request_2');simulation.applyLivingMindDecision({agentId:agent.id,requestId:'request_2',requestedTick:0,decision:{...waitDecision,current_intention:'Prověřit rozpor.',reason_for_change:'Nový důkaz odporuje očekávání.'},provider:'test',model:'test',latencyMs:5,fallback:false});expect(agent.intention).toBe('Prověřit rozpor.');expect(agent.mind.intentionReason).toContain('důkaz')});
  it('ignores stale decisions and clears pending state',()=>{const simulation=new Simulation(createWorld(3,1),3,1,'LIVING_MIND');const agent=simulation.state.agents[0];agent.lastDecisionTick=-100;simulation.prepareLivingMindRequest(agent.id,'stale');for(let i=0;i<181;i++)simulation.tick();expect(simulation.applyLivingMindDecision({agentId:agent.id,requestId:'stale',requestedTick:0,decision:waitDecision,provider:'test',model:'test',latencyMs:5,fallback:false})).toBe(false);expect(agent.mind.pendingRequestId).toBeUndefined();expect(simulation.state.ai.totals.staleCount).toBe(1)});
  it('keeps personal memories owned by one inhabitant',()=>{const state=createWorld(4,2);const memory:Memory={id:'private',tick:0,day:1,type:'episodic',text:'Osobní zkušenost.',importance:.8,participants:[],location:{x:1,y:1},tags:[]};state.agents[0].memories.push(memory);expect(state.agents[1].memories).not.toContainEqual(memory)});
  it('transfers speech only to the nearby listener',()=>{const simulation=new Simulation(createWorld(5,3),5,3,'LIVING_MIND');const [speaker,listener,outsider]=simulation.state.agents;listener.x=speaker.x;listener.y=speaker.y;outsider.x=0;outsider.y=0;speaker.lastDecisionTick=-100;simulation.prepareLivingMindRequest(speaker.id,'speech');simulation.applyLivingMindDecision({agentId:speaker.id,requestId:'speech',requestedTick:0,decision:{thought_summary:'Chce sdílet vlastní pozorování.',current_intention:speaker.intention,action:{type:'SPEAK',targetAgentId:listener.id,speech:'U vody jsem viděl kámen.'},speech:'U vody jsem viděl kámen.'},provider:'test',model:'test',latencyMs:5,fallback:false});expect(listener.memories.some(memory=>memory.text.includes('U vody'))).toBe(true);expect(outsider.memories.some(memory=>memory.text.includes('U vody'))).toBe(false)});
  it('records contradictory evidence without replacing reality',()=>{const agent=createWorld(6,1).agents[0];agent.beliefs.push({id:'belief',statement:'Zakrytí z větví vydrží v mokré půdě.',status:'LIKELY',evidence:['Jednou vydrželo.'],confidence:.8,updatedTick:0});const changed=new LearningEngine().belief.contradiction(agent,'Zakrytí z větví se v mokré půdě rozpadlo.',20);expect(changed?.status).toBe('UNCERTAIN');expect(changed?.confidence).toBeLessThan(.8);expect(agent.beliefs).toHaveLength(1)});
  it('detects meaningful reflection boundaries',()=>{const engine=new ReflectionEngine();const agent=createWorld(7,1).agents[0];agent.lastReflectionTick=0;expect(engine.shouldReflect(agent,'Pokus selhal a rozpadl se.',100)).toBe(true);expect(engine.shouldReflect(agent,'Prošel jsem travou.',100)).toBe(false)});
  it('builds bounded local and personal context',()=>{const state=createWorld(8,3);const agent=state.agents[0];const context=new CognitiveCore().buildMindContext(state,agent);expect(context.perception.objects.length).toBeLessThanOrEqual(30);expect(context.relevantMemories.length).toBeLessThanOrEqual(8);expect(context.relevantBeliefs.length).toBeLessThanOrEqual(6);expect(context).not.toHaveProperty('tiles');expect(context.identity.name).toBe(agent.name)});
  it('continues ticking while an external decision is delayed',async()=>{class SlowProvider implements AIProvider{readonly name='slow';readonly model='test';async generateDecision():Promise<AIProviderResult>{await new Promise(resolve=>setTimeout(resolve,30));return {decision:waitDecision}}async generateReflection(){return ''}async generateMemoryConsolidation(){return ''}}const simulation=new Simulation(createWorld(9,1),9,1,'LIVING_MIND');const agent=simulation.state.agents[0];agent.lastDecisionTick=-100;const context=simulation.prepareLivingMindRequest(agent.id,'delayed') as MindDecisionContext;const scheduler=new AIRequestScheduler(new SlowProvider(),{maxConcurrency:1,timeoutMs:200,maxQueue:5});const pending=scheduler.schedule({requestId:'delayed',agentId:agent.id,requestedTick:context.requestTick,context,fallback:()=>simulation.fallbackDecision(agent.id)});for(let i=0;i<5;i++)simulation.tick();expect(simulation.state.tick).toBe(5);const result=await pending;expect(simulation.applyLivingMindDecision(result)).toBe(true)});
});
