import type { Agent, AgentAction, Belief, ExperienceRecord, Memory, SimulationState } from '@novus/shared';
import { simulationCs, uid } from '@novus/shared';
export class PatternDetector { detect(agent:Agent){const last=agent.actionHistory.slice(-8).map(a=>a.type);if(last.length<6)return {repetitive:false,pattern:''};const unique=new Set(last);return {repetitive:unique.size<=2,pattern:last.join(' → ')}} }
export class NoveltyDetector { score(agent:Agent){const actions=agent.actionHistory.slice(-12);return new Set(actions.map(a=>`${a.type}:${a.description||''}`)).size/Math.max(1,actions.length)} }
export class BeliefUpdater {
  fromObservation(agent:Agent,observation:string,tick:number):Belief|null{
    if(!/(nečekan|zdá|všiml|zlom|mokr|u vody|vydrž|unexpected|seems|noticed|broke|wet|near water|held)/i.test(observation))return null;const subject=observation.replace(/^(I |Já )/,'').slice(0,120);const old=agent.beliefs.find(b=>b.statement.toLowerCase()===subject.toLowerCase());if(old){old.evidence.push(observation);old.confidence=Math.min(.96,old.confidence+.12);old.status=old.confidence>.78?'LIKELY':old.status;old.updatedTick=tick;return old}const belief={id:uid('belief',tick),statement:subject,status:'HYPOTHESIS' as const,evidence:[observation],confidence:.34,updatedTick:tick};agent.beliefs.push(belief);return belief;
  }
  contradiction(agent:Agent,observation:string,tick:number){const tokens=new Set(observation.toLowerCase().match(/[\p{L}]{4,}/gu)||[]);const belief=agent.beliefs.find(item=>[...tokens].some(token=>item.statement.toLowerCase().includes(token))&&/(ne|nikoli|selhal|rozpadl|opač|nečekan)/i.test(observation));if(!belief)return null;belief.evidence.push(`Rozporný důkaz: ${observation}`);belief.confidence=Math.max(.08,belief.confidence-.18);belief.status=belief.confidence<.22?'DISPUTED':'UNCERTAIN';belief.updatedTick=tick;return belief}
}
export class SkillExtractor { fromSuccess(agent:Agent,action:AgentAction,result:string,tick:number){if(!/(uspěl|vydržel|vytvořil|held|created)/i.test(result)||!['CRAFT_EXPERIMENT','BUILD'].includes(action.type))return null;const name=action.type==='BUILD'?simulationCs.learning.coveringSkill:simulationCs.learning.combinationSkill;const found=agent.skills.find(s=>s.name===name);if(found){found.attempts++;found.successes++;found.confidence=Math.min(.95,found.confidence+.12);found.lastUsed=tick;return found}const skill={id:uid('skill',tick),name,description:result,origin:simulationCs.learning.origin(Math.max(1,Math.floor(tick/1440)+1)),supportingExperiences:[result],steps:[action.description||simulationCs.learning.observeMaterials,simulationCs.learning.repeatArrangement],confidence:.48,lastUsed:tick,successes:1,attempts:1};agent.skills.push(skill);return skill} }
export class MemoryConsolidator { consolidate(agent:Agent,tick:number){const raw=agent.memories.filter(m=>m.type==='working').slice(-6);if(raw.length<3)return null;const text=simulationCs.learning.pattern(raw.map(m=>m.text).join('; ').slice(0,260));const memory:Memory={id:uid('semantic',tick),tick,day:Math.floor(tick/1440)+1,type:'semantic',text,importance:.62,participants:[...new Set(raw.flatMap(m=>m.participants))],location:{x:agent.x,y:agent.y},tags:['consolidated','pattern']};agent.memories.push(memory);if(agent.memories.length>260)agent.memories.splice(0,agent.memories.length-260);return memory} }
export class ExperienceEvaluator { importance(result:string){return /(nečekan|selhal|uspěl|zran|první|naučil|unexpected|failed|succeeded|injur|first|learned)/i.test(result)?.85:.35} }
export class LearningDatasetCollector { record(state:SimulationState,agent:Agent,action:AgentAction,result:string,context:string):ExperienceRecord{const row={id:uid('experience',state.tick),agentId:agent.id,tick:state.tick,context,relevantMemories:agent.mind.lastRelevantMemoryIds.map(id=>agent.memories.find(memory=>memory.id===id)?.text).filter((text):text is string=>Boolean(text)),beliefs:agent.beliefs.slice(-6).map(b=>b.statement),motivations:agent.motivations.slice(0,5).map(m=>m.text),identitySnapshot:`${agent.biography} ${agent.character} ${agent.mind.identityDevelopments.join(' ')}`.slice(0,1200),mode:state.ai.mode,decision:agent.intention,action,expectedOutcome:agent.mind.expectedOutcome,worldResult:result};state.experiences.push(row);if(state.experiences.length>4000)state.experiences.shift();return row} }
export class LearningEngine { pattern=new PatternDetector(); novelty=new NoveltyDetector(); belief=new BeliefUpdater(); skill=new SkillExtractor(); memory=new MemoryConsolidator(); evaluator=new ExperienceEvaluator(); dataset=new LearningDatasetCollector();process(state:SimulationState,agent:Agent,action:AgentAction,result:string){const before=agent.beliefs.length;const changed=this.belief.fromObservation(agent,result,state.tick);const contradiction=this.belief.contradiction(agent,result,state.tick);if(changed||contradiction)state.ai.research.beliefChanges++;if(contradiction)state.ai.research.contradictions++;this.skill.fromSuccess(agent,action,result,state.tick);this.dataset.record(state,agent,action,result,agent.recentObservations.join(' '));if(state.tick-agent.lastReflectionTick>240)this.memory.consolidate(agent,state.tick);return {beliefCreated:agent.beliefs.length>before,contradiction}} }
