'use client';
import { useEffect,useRef } from 'react';import type { SimulationState,TileType } from '@novus/shared';
const COLORS:Record<TileType,number>={grass:0x66764a,dirt:0x79674b,fertile:0x73804d,sand:0xa69a6a,shallow_water:0x4e7e7d,deep_water:0x345f6b,rock:0x64655b};
export default function WorldCanvas({state,selectedId,onSelect}:{state:SimulationState;selectedId:string|null;onSelect:(id:string)=>void}){const host=useRef<HTMLDivElement>(null);const runtime=useRef<any>(null);const selectRef=useRef(onSelect);selectRef.current=onSelect;
  useEffect(()=>{let disposed=false;let ro:ResizeObserver;void (async()=>{const PIXI=await import('pixi.js');if(disposed||!host.current)return;const app=new PIXI.Application();await app.init({resizeTo:host.current,antialias:true,background:COLORS.grass,resolution:Math.min(devicePixelRatio,2),autoDensity:true});if(disposed){app.destroy(true);return}host.current.appendChild(app.canvas);const world=new PIXI.Container();app.stage.addChild(world);world.position.set(app.screen.width/2-1000,app.screen.height/2-1000);world.scale.set(.72);const tileSize=20;
    for(let cy=0;cy<7;cy++)for(let cx=0;cx<7;cx++){const g=new PIXI.Graphics();for(let y=cy*16;y<Math.min(state.height,(cy+1)*16);y++)for(let x=cx*16;x<Math.min(state.width,(cx+1)*16);x++){const t=state.tiles[y*state.width+x];g.rect(x*tileSize,y*tileSize,tileSize+.5,tileSize+.5).fill(COLORS[t.type])}world.addChild(g)}
    const decor=new PIXI.Container();world.addChild(decor);for(const object of state.objects){const g=new PIXI.Graphics();if(object.kind==='tree'){g.ellipse(0,4,15,10).fill({color:0x17251a,alpha:.28});g.circle(0,0,7.5).fill(object.id.charCodeAt(5)%2?0x29432c:0x355035);g.circle(-3,-4,4).fill(0x405a39)}else if(object.kind==='stone'){g.ellipse(0,2,5,3.5).fill(0x858579)}else if(object.kind==='berries'){g.circle(0,0,4).fill(0x405b34);g.circle(2,-1,1.4).fill(0x683d4f)}else if(object.kind==='branch'){g.rect(-5,-1,10,2).fill(0x5c4129);g.rotation=.45}else if(object.kind==='bush'){g.circle(0,0,5).fill(0x40553a)}else{g.rect(-4,-3,8,6).fill(0xd0c69d)}g.position.set(object.x*tileSize+10,object.y*tileSize+10);decor.addChild(g)}
    const structures=new PIXI.Container();world.addChild(structures);const agents=new PIXI.Container();world.addChild(agents);const weather=new PIXI.Graphics();app.stage.addChild(weather);runtime.current={PIXI,app,world,agents,structures,weather,tileSize,agentViews:new Map(),structureIds:new Set()};
    let dragging=false,last={x:0,y:0};app.stage.eventMode='static';app.stage.hitArea=app.screen;app.stage.on('pointerdown',(e:any)=>{dragging=true;last={x:e.global.x,y:e.global.y}});app.stage.on('pointerup',()=>dragging=false);app.stage.on('pointerupoutside',()=>dragging=false);app.stage.on('pointermove',(e:any)=>{if(!dragging)return;world.x+=e.global.x-last.x;world.y+=e.global.y-last.y;last={x:e.global.x,y:e.global.y}});app.canvas.addEventListener('wheel',e=>{e.preventDefault();const next=Math.max(.28,Math.min(2.1,world.scale.x*(e.deltaY<0?1.12:.89)));world.scale.set(next)},{passive:false});
    ro=new ResizeObserver(()=>{app.resize();app.stage.hitArea=app.screen});ro.observe(host.current!);updateDynamic(state,selectedId,runtime.current,selectRef);})();return()=>{disposed=true;ro?.disconnect();runtime.current?.app?.destroy(true,{children:true});runtime.current=null}},[state.seed]);
  useEffect(()=>{if(runtime.current)updateDynamic(state,selectedId,runtime.current,selectRef)},[state.tick,selectedId,state.weather]);return <div className="pixi-host" ref={host} />}
function updateDynamic(state:SimulationState,selectedId:string|null,r:any,selectRef:any){const {PIXI,agents,agentViews,structures,structureIds,tileSize,weather,app}=r;for(const s of state.structures)if(!structureIds.has(s.id)){structureIds.add(s.id);const g=new PIXI.Graphics();g.rect(-7,-7,14,14).fill({color:s.progress>=1?0x6d5031:0x887452,alpha:.9});g.moveTo(-8,-8).lineTo(0,-14).lineTo(8,-8).stroke({color:0x3c3023,width:4});g.position.set(s.x*tileSize+10,s.y*tileSize+10);structures.addChild(g)}
  for(const agent of state.agents){let view=agentViews.get(agent.id);if(!view){const c=new PIXI.Container();c.eventMode='static';c.cursor='pointer';const shadow=new PIXI.Graphics().ellipse(0,7,8,4).fill({color:0x10150f,alpha:.45});const body=new PIXI.Graphics().roundRect(-5,-7,10,16,4).fill(parseInt(agent.appearance.clothing.includes('red')?'9b5f4b':agent.appearance.clothing.includes('blue')?'5a7880':'c3955f',16));const head=new PIXI.Graphics().circle(0,-8,4.5).fill(parseInt(agent.appearance.skin.slice(1),16));const ring=new PIXI.Graphics();const label=new PIXI.Text({text:agent.name,style:{fontFamily:'Georgia',fontSize:9,fill:0xf1edda,stroke:{color:0x0d1310,width:3}}});label.anchor.set(.5);label.y=-19;c.addChild(shadow,body,head,ring,label);c.on('pointertap',(e:any)=>{e.stopPropagation();selectRef.current(agent.id)});agents.addChild(c);view={c,ring,label};agentViews.set(agent.id,view)}view.c.position.set(agent.x*tileSize+10,agent.y*tileSize+10);view.ring.clear();if(agent.id===selectedId)view.ring.circle(0,1,11).stroke({color:0xe0c878,width:2,alpha:.95});view.label.visible=agent.id===selectedId||r.world.scale.x>.8}
  weather.clear();if(state.weather==='rain'){for(let i=0;i<90;i++){const x=(i*97+state.tick*3)%app.screen.width,y=(i*53+state.tick*8)%app.screen.height;weather.moveTo(x,y).lineTo(x-4,y+9)}weather.stroke({color:0xa7c5c8,width:1,alpha:.32})}const darkness=state.hour<5?Math.min(.58,(5-state.hour)*.1):state.hour>19?Math.min(.58,(state.hour-19)*.1):0;if(darkness)weather.rect(0,0,app.screen.width,app.screen.height).fill({color:0x111928,alpha:darkness})}
