import { z } from 'zod'; import { DEFAULT_LOCALE, simulationCs, type Agent, type Decision, type Perception } from '@novus/shared';
export const AI_LANGUAGE=process.env.AI_LANGUAGE||DEFAULT_LOCALE;
export const NEUTRAL_AGENT_PROMPT=`Existuješ nepřetržitě v trvalém světě společně s dalšími autonomními obyvateli. Pozorovatel tě neovládá a nemáš přidělené poslání. Tvé zkušenosti patří tobě. Pozoruj okolí, pamatuj si, co se děje, komunikuj, kdy chceš, vytvářej vlastní záměry, zpochybňuj předpoklady a rozhoduj se, jak jednat. Nepředpokládej existenci společenských struktur, tradic, institucí ani sdílených znalostí, pokud jsi je osobně nepozoroval, nezažil nebo se o nich nedozvěděl od jiného obyvatele. Opírej své chápání o prožité zkušenosti. Své názory a záměry můžeš časem měnit. Nemusíš být stále produktivní: můžeš odpočívat, pozorovat, přemýšlet, zkoumat, mluvit, znovu zvažovat nebo opustit svůj nápad. Když tě něco překvapí, můžeš to prozkoumat. Přemýšlej, komunikuj, vytvářej stručná shrnutí úvah, vzpomínky, přesvědčení i názvy nových pojmů přirozenou češtinou (${AI_LANGUAGE}).`;
const actionSchema=z.object({type:z.enum(['WAIT','MOVE','SPEAK','INSPECT','PICK_UP','DROP','GATHER','PLACE','BUILD','USE','CRAFT_EXPERIMENT','GIVE','TAKE','WRITE','READ']),target:z.object({x:z.number(),y:z.number()}).optional(),objectId:z.string().optional(),description:z.string().max(500).optional(),targetAgentId:z.string().optional(),speech:z.string().max(500).optional()});
export const decisionSchema=z.object({thought_summary:z.string().max(700),current_intention:z.string().max(700),action:actionSchema,speech:z.string().max(500).nullable()});
export interface AIContext { agent:Agent; perception:Perception; memories:string[]; beliefs:string[]; }
export interface AIProvider { readonly name:string; generateDecision(context:AIContext):Promise<Decision>; generateReflection(context:AIContext,result:string):Promise<string>; generateMemoryConsolidation(context:AIContext):Promise<string>; }
export class MockAIProvider implements AIProvider {readonly name='mock';async generateDecision():Promise<Decision>{return {thought_summary:simulationCs.ai.mockThought,current_intention:simulationCs.ai.mockIntention,action:{type:'WAIT'},speech:null}}async generateReflection(_:AIContext,result:string){return simulationCs.ai.reflection(result)}async generateMemoryConsolidation(context:AIContext){return context.memories.slice(-3).join(' ')} }
export class OpenAICompatibleProvider implements AIProvider {
  readonly name='openai-compatible';constructor(private config={baseUrl:process.env.AI_BASE_URL||'https://api.openai.com/v1',apiKey:process.env.AI_API_KEY||'',model:process.env.AI_MODEL||'gpt-4.1-mini'}){}
  private async request(prompt:string){let last:unknown;for(let attempt=0;attempt<3;attempt++){try{const response=await fetch(`${this.config.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${this.config.apiKey}`},body:JSON.stringify({model:this.config.model,response_format:{type:'json_object'},messages:[{role:'system',content:NEUTRAL_AGENT_PROMPT},{role:'user',content:prompt}]})});if(!response.ok)throw new Error(`AI ${response.status}`);const json=await response.json() as any;return String(json.choices?.[0]?.message?.content||'')}catch(error){last=error;await new Promise(r=>setTimeout(r,250*2**attempt))}}throw last}
  async generateDecision(context:AIContext){const raw=await this.request(`Vnímání: ${JSON.stringify(context.perception)}\nRelevantní vzpomínky: ${JSON.stringify(context.memories)}\nPřesvědčení: ${JSON.stringify(context.beliefs)}\nVrať pouze strukturované rozhodnutí v češtině (${AI_LANGUAGE}).`);try{return decisionSchema.parse(JSON.parse(raw))}catch{return {thought_summary:simulationCs.ai.fallbackThought,current_intention:simulationCs.ai.fallbackIntention,action:{type:'WAIT'},speech:null}}}
  async generateReflection(context:AIContext,result:string){return (await this.request(`Stručně česky zhodnoť tento výsledek bez skrytého řetězce úvah: ${result}. Současný záměr: ${context.agent.intention}`)).slice(0,700)}async generateMemoryConsolidation(context:AIContext){return (await this.request(`Vytvoř stručné české zobecnění z těchto zkušeností: ${context.memories.join('; ')}`)).slice(0,700)}
}
export const createAIProvider=()=>process.env.AI_API_KEY?new OpenAICompatibleProvider():new MockAIProvider();
